import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { WallpapersService } from '../wallpapers/wallpapers.service';
import { SystemConfigService } from '../system-config/system-config.service';
import axios from 'axios';
import * as fs from 'fs';
import { join } from 'path';
import { v4 as uuidv4 } from 'uuid';
@Injectable()
export class AiService {
    private readonly logger = new Logger(AiService.name);

    constructor(
        private configService: ConfigService,
        private wallpapersService: WallpapersService,
        private systemConfigService: SystemConfigService,
    ) { }

    async generateImage(prompt: string): Promise<string> {
        // 1. Try to get from Database first
        const dbApiKey = await this.systemConfigService.get('AI_API_KEY');
        const dbApiUrl = await this.systemConfigService.get('AI_API_URL');
        const dbModel = await this.systemConfigService.get('AI_MODEL');

        // 2. Fallback to .env if DB is empty
        const apiKey = dbApiKey || this.configService.get<string>('AI_API_KEY');
        const apiUrl = dbApiUrl || this.configService.get<string>('AI_API_URL') || 'https://api.openai.com/v1/images/generations';
        const model = dbModel || this.configService.get<string>('AI_MODEL') || 'dall-e-3';

        if (!apiKey) {
            this.logger.warn('AI_API_KEY is not set. Returning a mock image.');
            return `https://picsum.photos/seed/${encodeURIComponent(prompt)}/1024/1792`;
        }

        try {
            this.logger.log(`Generating image for prompt: ${prompt} using model: ${model}`);

            // Universal OpenAI-compatible format
            const response = await axios.post(
                apiUrl,
                {
                    model: model,
                    prompt: prompt,
                    n: 1,
                    size: '1024x1792', // Portrait for wallpapers
                    response_format: 'url',
                },
                {
                    headers: {
                        Authorization: `Bearer ${apiKey}`,
                        'Content-Type': 'application/json',
                    },
                    timeout: 60000,
                },
            );

            const imageUrl = response.data?.data?.[0]?.url || response.data?.images?.[0]?.url;
            if (!imageUrl) {
                throw new Error('No image URL in response');
            }

            return imageUrl;
        } catch (error) {
            this.logger.error('AI Generation Failed', error.response?.data || error.message);
            throw new Error(`AI生成失败: ${error.response?.data?.error?.message || error.message}`);
        }
    }

    async saveToGallery(data: { url: string; title: string; description?: string }) {
        // 1. Download image to local uploads
        const filename = `ai-${uuidv4()}.jpg`;
        const uploadPath = join(__dirname, '..', '..', '..', 'uploads');
        if (!fs.existsSync(uploadPath)) {
            fs.mkdirSync(uploadPath, { recursive: true });
        }
        const filePath = join(uploadPath, filename);

        try {
            const response = await axios({
                method: 'get',
                url: data.url,
                responseType: 'stream'
            });

            const writer = fs.createWriteStream(filePath);
            response.data.pipe(writer);

            await new Promise<void>((resolve, reject) => {
                writer.on('finish', () => resolve());
                writer.on('error', (err) => reject(err));
            });

            // 2. Call wallpapersService to create record (mimicking a normal upload)
            // Note: Creating a fake "file" object to reuse wallpapersService logic
            const mockFile = {
                path: filePath,
                filename: filename,
                destination: uploadPath,
                fieldname: 'file'
            } as any;

            // WallpapersService expects categories as a string comma separated
            // We'll assign a default 'AI生成' category if it exists, otherwise leave blank
            return this.wallpapersService.create({
                title: data.title,
                description: data.description || 'Generated by AI',
                categories: 'AI生成',
                url: `/uploads/${filename}`,
                thumb: `/uploads/${filename}`, // Initial thumb, wallpapersService usually handles this
                status: 'PENDING'
            });
        } catch (err) {
            this.logger.error('Failed to save AI image', err);
            throw err;
        }
    }
}
